image: scorpil/rust:nightly

stages:
  - test
  - build

before_script:
  - apt-get update
  - apt-get upgrade --yes
  - apt-get --yes --fix-missing install libcurl4-openssl-dev libelf-dev libdw-dev cmake build-essential pkg-config cmake-data zlib1g zlib1g-dev python libsdl2-dev libsdl2-image-dev libpulse-dev

'Tests':
  stage: test
  script:
    - cargo test

'Build Debug':
  stage: build
  script:
    - cargo build
  artifacts:
    name: "musicpi-display-${CI_BUILD_REF_NAME}-debug"
    paths:
      - target/debug/*

'Build Release':
  stage: build
  script:
    - cargo build --release
  artifacts:
    name: "musicpi-display-${CI_BUILD_REF_NAME}-release"
    paths:
      - target/release/*

'Build Documentation':
  stage: build
  script:
    - cargo doc
  artifacts:
    name: "musicpi-display-${CI_BUILD_REF_NAME}-doc"
    paths:
      - target/doc/*
