image: "liuchong/rustup:nightly"

stages:
  - test
  - build

before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential cmake libsdl2-dev libsdl2-image-dev libpulse-dev
  - rustup update

'Tests':
  stage: test
  script:
    - cargo test

'Build Debug':
  stage: build
  script:
    - cargo build
  artifacts:
    name: "musicpi-display-${CI_BUILD_REF_NAME}-debug"
    paths:
      - target/debug/*

'Build Release':
  stage: build
  script:
    - cargo build --release
  artifacts:
    name: "musicpi-display-${CI_BUILD_REF_NAME}-release"
    paths:
      - target/release/*

'Build Documentation':
  stage: build
  script:
    - cargo doc
  artifacts:
    name: "musicpi-display-${CI_BUILD_REF_NAME}-doc"
    paths:
      - target/doc/*
